services:
  hello-world:
    image: ghcr.io/oriolrius/hello-world:v4
    ports:
      - "49000:49000"
    restart: unless-stopped
   whoami:
    image: traefik/whoami
    ports:
      - "49001:80"
    restart: unless-stopped
